imports

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, balanced_accuracy_score
from sklearn.model_selection import StratifiedKFold, cross_validate

In [3]:

def preprocess(file_path,split_value,target_column_index,has_header,delete_list,extraction_list):
    """this function is used for taking the dataset from .csv file making a test train split
    and x, y split (has header is either True or False)"""

    #reading the .csv
    if has_header:
        df = pd.read_csv(file_path, header=0, delimiter=",")  # First row as header
        print(f"Dataset shape: {df.shape}")
        print(f"Column names: {list(df.columns)}")
    else:
        df = pd.read_csv(file_path, header=None, delimiter=",")  # No header row
        print(f"Dataset shape: {df.shape}")

    
    #making target variable split
    x_ds = df.drop(df.columns[target_column_index], axis=1)  # All except target
    y_ds = df.iloc[:, target_column_index]  # Target column only

    x_ds = x_ds.drop(columns = delete_list + extraction_list)
    #making test train split
    x_train, x_test, y_train, y_test = train_test_split(x_ds, y_ds, test_size=split_value, random_state=10, shuffle= True)
    print(f'shape of x training: {x_train.shape}')
    print(f'shape of x testing: {x_test.shape}')

    return x_train, x_test, y_train, y_test, x_ds, y_ds

In [4]:
def implement(model, x_train, y_train, x_test, y_test, x_ds, y_ds):
    """this function contains implementation (modeling and fitting) on the dataset with 1 
    initiation and shows the results of the implementations.
    Note: This function doesn't have compile so it is not appoprate to use this function for perceptron learning algs.
    because it doesn't have training vs test accuracy comparison and doesn't have epochs and .argmax(axis=1) """
    #initiante ml
    model.fit(x_train, y_train)
    #model evaluation
    y_pred = model.predict(x_test)

    print(f'Confusion matrix: \n{confusion_matrix(y_test, y_pred)}')
    print(f'Classification report: {classification_report(y_test, y_pred)}')
    print(f"Accuracy score is: {accuracy_score(y_test,y_pred):.3f}")
    print(f"Balanced accuracy score is: {balanced_accuracy_score(y_test,y_pred):.3f}")
    print(f"Precision score is: {precision_score(y_test,y_pred, average='weighted'):.3f}")
    print(f"Recall score is: {recall_score(y_test,y_pred, average='weighted'):.3f}")
    
    # StratifiedKFold evaluations
    skf = StratifiedKFold(n_splits=10, shuffle=True, random_state=10)
    scoring = ['balanced_accuracy', 'accuracy', 'precision_weighted', 'recall_weighted']
    cv_results = cross_validate(model, x_ds, y_ds, cv=skf, scoring=scoring)

    #if type(model) == KNeighborsClassifier:
    #    knn_cv_bacc = round(cv_results['test_balanced_accuracy'].mean(),3)
    #    knn_cv_precision = round(cv_results['test_precision_weighted'].mean(),3)
    #    knn_cv_recall = round(cv_results['test_recall_weighted'].mean(),3)
        

    print(f"StratifiedKFold CV Balanced Accuracy: {cv_results['test_balanced_accuracy'].mean():.3f}\\scriptsize(±{cv_results['test_balanced_accuracy'].std() * 2:.2f})")
    print(f"StratifiedKFold CV Accuracy: {cv_results['test_accuracy'].mean():.3f}\\scriptsize(±{cv_results['test_accuracy'].std() * 2:.2f})")
    print(f"StratifiedKFold CV Precision: {cv_results['test_precision_weighted'].mean():.3f}\\scriptsize(±{cv_results['test_precision_weighted'].std() * 2:.2f})")
    print(f"StratifiedKFold CV Recall: {cv_results['test_recall_weighted'].mean():.3f}\\scriptsize(±{cv_results['test_recall_weighted'].std() * 2:.2f})")

    return cv_results 
        

Select the dataset!

Runs the preprocess for diffrent datasets.

In [5]:
x_train1, x_test1, y_train1, y_test1, x_ds1, y_ds1 = preprocess("beans_kmeans.csv", 0.2, 16, True, [], [])

Dataset shape: (13611, 17)
Column names: ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4', 'Class']
shape of x training: (10888, 16)
shape of x testing: (2723, 16)


In [6]:
x_train2, x_test2, y_train2, y_test2, x_ds2, y_ds2 = preprocess("beans_kmeans.csv", 0.2, 16, True, [],["ShapeFactor4","Compactness","ShapeFactor3","Eccentricity","Solidity","Extent"] )

Dataset shape: (13611, 17)
Column names: ['Area', 'Perimeter', 'MajorAxisLength', 'MinorAxisLength', 'AspectRation', 'Eccentricity', 'ConvexArea', 'EquivDiameter', 'Extent', 'Solidity', 'roundness', 'Compactness', 'ShapeFactor1', 'ShapeFactor2', 'ShapeFactor3', 'ShapeFactor4', 'Class']
shape of x training: (10888, 10)
shape of x testing: (2723, 10)


x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("diabetes_kmeans.csv", 0.2, 8, True, [], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("diabetes_kmeans.csv", 0.2, 8, True, [], [])

In [7]:
x_train3, x_test3, y_train3, y_test3, x_ds3, y_ds3 = preprocess("divorce.csv", 0.2, 54, True, [], [])

Dataset shape: (170, 55)
Column names: ['Atr1', 'Atr2', 'Atr3', 'Atr4', 'Atr5', 'Atr6', 'Atr7', 'Atr8', 'Atr9', 'Atr10', 'Atr11', 'Atr12', 'Atr13', 'Atr14', 'Atr15', 'Atr16', 'Atr17', 'Atr18', 'Atr19', 'Atr20', 'Atr21', 'Atr22', 'Atr23', 'Atr24', 'Atr25', 'Atr26', 'Atr27', 'Atr28', 'Atr29', 'Atr30', 'Atr31', 'Atr32', 'Atr33', 'Atr34', 'Atr35', 'Atr36', 'Atr37', 'Atr38', 'Atr39', 'Atr40', 'Atr41', 'Atr42', 'Atr43', 'Atr44', 'Atr45', 'Atr46', 'Atr47', 'Atr48', 'Atr49', 'Atr50', 'Atr51', 'Atr52', 'Atr53', 'Atr54', 'Class']
shape of x training: (136, 54)
shape of x testing: (34, 54)


In [8]:
x_train4, x_test4, y_train4, y_test4, x_ds4, y_ds4 = preprocess("divorce.csv", 0.2, 54, True, [], ['Atr53','Atr7','Atr47','Atr48','Atr52','Atr43','Atr45','Atr6','Atr46'])

Dataset shape: (170, 55)
Column names: ['Atr1', 'Atr2', 'Atr3', 'Atr4', 'Atr5', 'Atr6', 'Atr7', 'Atr8', 'Atr9', 'Atr10', 'Atr11', 'Atr12', 'Atr13', 'Atr14', 'Atr15', 'Atr16', 'Atr17', 'Atr18', 'Atr19', 'Atr20', 'Atr21', 'Atr22', 'Atr23', 'Atr24', 'Atr25', 'Atr26', 'Atr27', 'Atr28', 'Atr29', 'Atr30', 'Atr31', 'Atr32', 'Atr33', 'Atr34', 'Atr35', 'Atr36', 'Atr37', 'Atr38', 'Atr39', 'Atr40', 'Atr41', 'Atr42', 'Atr43', 'Atr44', 'Atr45', 'Atr46', 'Atr47', 'Atr48', 'Atr49', 'Atr50', 'Atr51', 'Atr52', 'Atr53', 'Atr54', 'Class']
shape of x training: (136, 45)
shape of x testing: (34, 45)


In [9]:
x_train5, x_test5, y_train5, y_test5, x_ds5, y_ds5 = preprocess("parkinsons_kmeans.csv", 0.2, 17, True, ['name'], [])

Dataset shape: (195, 24)
Column names: ['name', 'MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)', 'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP', 'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5', 'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA', 'spread1', 'spread2', 'D2', 'PPE']
shape of x training: (156, 22)
shape of x testing: (39, 22)


In [10]:
x_train6, x_test6, y_train6, y_test6, x_ds6, y_ds6 = preprocess("parkinsons_kmeans.csv", 0.2, 17, True, ['name'], ['DFA','MDVP:Fo(Hz)','MDVP:Fhi(Hz)','MDVP:Flo(Hz)'])

Dataset shape: (195, 24)
Column names: ['name', 'MDVP:Fo(Hz)', 'MDVP:Fhi(Hz)', 'MDVP:Flo(Hz)', 'MDVP:Jitter(%)', 'MDVP:Jitter(Abs)', 'MDVP:RAP', 'MDVP:PPQ', 'Jitter:DDP', 'MDVP:Shimmer', 'MDVP:Shimmer(dB)', 'Shimmer:APQ3', 'Shimmer:APQ5', 'MDVP:APQ', 'Shimmer:DDA', 'NHR', 'HNR', 'status', 'RPDE', 'DFA', 'spread1', 'spread2', 'D2', 'PPE']
shape of x training: (156, 18)
shape of x testing: (39, 18)


In [11]:
x_train7, x_test7, y_train7, y_test7, x_ds7, y_ds7 = preprocess("rice_binned_kmeans.csv", 0.2, 7, True, [], [])

Dataset shape: (3810, 8)
Column names: ['Area', 'Perimeter', 'Major_Axis_Length', 'Minor_Axis_Length', 'Eccentricity', 'Convex_Area', 'Extent', 'Class']
shape of x training: (3048, 7)
shape of x testing: (762, 7)


In [12]:
x_train8, x_test8, y_train8, y_test8, x_ds8, y_ds8 = preprocess("rice_binned_kmeans.csv", 0.2, 7, True, [], ['Minor_Axis_Length', 'Extent'])

Dataset shape: (3810, 8)
Column names: ['Area', 'Perimeter', 'Major_Axis_Length', 'Minor_Axis_Length', 'Eccentricity', 'Convex_Area', 'Extent', 'Class']
shape of x training: (3048, 5)
shape of x testing: (762, 5)


x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("wdbc_binned_kmeans.csv", 0.2, 1, True, ['ID'], [])

x_train, x_test, y_train, y_test, x_ds, y_ds = preprocess("wdbc_binned_kmeans.csv", 0.2, 1, True, ['ID'], [])

Run the implement function for diffrent models

In [13]:
def compute_model_differences(model_name, globals_dict):
    """
    Creates variables like knn_0_bacc, knn_1_precision, etc.
    Each value formatted for LaTeX:
      e.g. '+0.011 \\scriptsize(%1)' or '-0.002 \\scriptsize(%0.2)'
    If diff == 0 → '0'
    """
    metrics = {
        "bacc": "balanced_accuracy",
        "precision": "precision_weighted",
        "recall": "recall_weighted"
    }

    for i in range(0, 8, 2):  # pairs: (1,2), (3,4), (5,6), (7,8)
        idx = i // 2
        cv_a = globals_dict[f"cv_results{i+1}"]
        cv_b = globals_dict[f"cv_results{i+2}"]

        for short, metric in metrics.items():
            var_name = f"{model_name}_{idx}_{short}"

            mean_a = cv_a[f"test_{metric}"].mean()
            mean_b = cv_b[f"test_{metric}"].mean()
            diff = round(mean_b - mean_a, 3)

            if diff == 0:
                formatted = "0"
            else:
                pct = round(abs(diff / mean_a * 100), 1)
                sign = "+" if diff > 0 else ""
                formatted = f"{sign}{diff:.3f} \\scriptsize(\\%{pct})"

            globals_dict[var_name] = formatted


In [14]:
#KNN
from sklearn.neighbors import KNeighborsClassifier
cv_results1 = implement(KNeighborsClassifier(),
                     x_train1, y_train1, x_test1, y_test1, x_ds1, y_ds1)

cv_results2 = implement(KNeighborsClassifier(),
                     x_train2, y_train2, x_test2, y_test2, x_ds2, y_ds2)

cv_results3 = implement(KNeighborsClassifier(),
                     x_train3, y_train3, x_test3, y_test3, x_ds3, y_ds3)

cv_results4 = implement(KNeighborsClassifier(),
                     x_train4, y_train4, x_test4, y_test4, x_ds4, y_ds4)

cv_results5 = implement(KNeighborsClassifier(),
                     x_train5, y_train5, x_test5, y_test5, x_ds5, y_ds5)

cv_results6 = implement(KNeighborsClassifier(),
                     x_train6, y_train6, x_test6, y_test6, x_ds6, y_ds6)

cv_results7 = implement(KNeighborsClassifier(),
                     x_train7, y_train7, x_test7, y_test7, x_ds7, y_ds7)

cv_results8 = implement(KNeighborsClassifier(),
                     x_train8, y_train8, x_test8, y_test8, x_ds8, y_ds8)


compute_model_differences("knn", globals())


Confusion matrix: 
[[213   0  14   0   1   1   4]
 [  0 117   1   0   0   0   0]
 [ 11   0 310   0   6   1   2]
 [  0   0   0 645   0   8  53]
 [  0   0   7   5 370   0  14]
 [  4   0   0  12   0 384  11]
 [  1   0   2  62   5   8 451]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.93      0.91      0.92       233
      BOMBAY       1.00      0.99      1.00       118
        CALI       0.93      0.94      0.93       330
    DERMASON       0.89      0.91      0.90       706
       HOROZ       0.97      0.93      0.95       396
       SEKER       0.96      0.93      0.94       411
        SIRA       0.84      0.85      0.85       529

    accuracy                           0.91      2723
   macro avg       0.93      0.93      0.93      2723
weighted avg       0.92      0.91      0.91      2723

Accuracy score is: 0.914
Balanced accuracy score is: 0.926
Precision score is: 0.915
Recall score is: 0.914
StratifiedKFold CV Balanced Accurac

knn_0_bacc= round(cv_results2['test_balanced_accuracy'].mean() - cv_results1['test_balanced_accuracy'].mean(), 3)
knn_1_bacc= round(cv_results4['test_balanced_accuracy'].mean() - cv_results3['test_balanced_accuracy'].mean(), 3)
knn_2_bacc= round(cv_results6['test_balanced_accuracy'].mean() - cv_results5['test_balanced_accuracy'].mean(), 3)
knn_3_bacc= round(cv_results8['test_balanced_accuracy'].mean() - cv_results7['test_balanced_accuracy'].mean(), 3)

knn_0_precision= round(cv_results2['test_precision_weighted'].mean() - cv_results1['test_precision_weighted'].mean(), 3)
knn_1_precision= round(cv_results4['test_precision_weighted'].mean() - cv_results3['test_precision_weighted'].mean(), 3)
knn_2_precision= round(cv_results6['test_precision_weighted'].mean() - cv_results5['test_precision_weighted'].mean(), 3)
knn_3_precision= round(cv_results8['test_precision_weighted'].mean() - cv_results7['test_precision_weighted'].mean(), 3)

knn_0_recall= round(cv_results2['test_recall_weighted'].mean() - cv_results1['test_recall_weighted'].mean(), 3)
knn_1_recall= round(cv_results4['test_recall_weighted'].mean() - cv_results3['test_recall_weighted'].mean(), 3)
knn_2_recall= round(cv_results6['test_recall_weighted'].mean() - cv_results5['test_recall_weighted'].mean(), 3)
knn_3_recall= round(cv_results8['test_recall_weighted'].mean() - cv_results7['test_recall_weighted'].mean(), 3)

In [15]:
#Ada Boost
from sklearn.ensemble import AdaBoostClassifier
cv_results1 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train1, y_train1, x_test1, y_test1, x_ds1, y_ds1)

cv_results2 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train2, y_train2, x_test2, y_test2, x_ds2, y_ds2)

cv_results3 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train3, y_train3, x_test3, y_test3, x_ds3, y_ds3)

cv_results4 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train4, y_train4, x_test4, y_test4, x_ds4, y_ds4)

cv_results5 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train5, y_train5, x_test5, y_test5, x_ds5, y_ds5)

cv_results6 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train6, y_train6, x_test6, y_test6, x_ds6, y_ds6)

cv_results7 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train7, y_train7, x_test7, y_test7, x_ds7, y_ds7)

cv_results8 = implement(AdaBoostClassifier(n_estimators=100, random_state=10),
                     x_train8, y_train8, x_test8, y_test8, x_ds8, y_ds8)

compute_model_differences("ada", globals())

Confusion matrix: 
[[173   0  50   0   5   1   4]
 [  0 118   0   0   0   0   0]
 [  6   0 247   0  75   1   1]
 [  0   0   0 559  10  25 112]
 [  1   0   3   2 380   0  10]
 [  8   0   0  25   0 367  11]
 [  3   0   2  39  20  27 438]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.91      0.74      0.82       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.82      0.75      0.78       330
    DERMASON       0.89      0.79      0.84       706
       HOROZ       0.78      0.96      0.86       396
       SEKER       0.87      0.89      0.88       411
        SIRA       0.76      0.83      0.79       529

    accuracy                           0.84      2723
   macro avg       0.86      0.85      0.85      2723
weighted avg       0.84      0.84      0.84      2723

Accuracy score is: 0.838
Balanced accuracy score is: 0.852
Precision score is: 0.844
Recall score is: 0.838


/Users/Can/VsCodeProjects/bitirme projesi/ppfs_mlpart/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/Can/VsCodeProjects/bitirme projesi/ppfs_mlpart/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/Can/VsCodeProjects/bitirme projesi/ppfs_mlpart/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` par

StratifiedKFold CV Balanced Accuracy: 0.772\scriptsize(±0.13)
StratifiedKFold CV Accuracy: 0.833\scriptsize(±0.06)
StratifiedKFold CV Precision: 0.832\scriptsize(±0.07)
StratifiedKFold CV Recall: 0.833\scriptsize(±0.06)
Confusion matrix: 
[[178   0  44   0   0   2   9]
 [  0   0 118   0   0   0   0]
 [131   0 187   0   9   1   2]
 [  0   0   0 564  11  90  41]
 [ 14   0   5   4 366   0   7]
 [  9   0   0   4   0 388  10]
 [  5   0   1  86  28  24 385]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.53      0.76      0.62       233
      BOMBAY       0.00      0.00      0.00       118
        CALI       0.53      0.57      0.55       330
    DERMASON       0.86      0.80      0.83       706
       HOROZ       0.88      0.92      0.90       396
       SEKER       0.77      0.94      0.85       411
        SIRA       0.85      0.73      0.78       529

    accuracy                           0.76      2723
   macro avg       0.63      0.6

/Users/Can/VsCodeProjects/bitirme projesi/ppfs_mlpart/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/Can/VsCodeProjects/bitirme projesi/ppfs_mlpart/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/Users/Can/VsCodeProjects/bitirme projesi/ppfs_mlpart/.venv/lib/python3.12/site-packages/sklearn/metrics/_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` par

StratifiedKFold CV Balanced Accuracy: 0.768\scriptsize(±0.15)
StratifiedKFold CV Accuracy: 0.830\scriptsize(±0.06)
StratifiedKFold CV Precision: 0.831\scriptsize(±0.07)
StratifiedKFold CV Recall: 0.830\scriptsize(±0.06)
Confusion matrix: 
[[17  0]
 [ 0 17]]
Classification report:               precision    recall  f1-score   support

           0       1.00      1.00      1.00        17
           1       1.00      1.00      1.00        17

    accuracy                           1.00        34
   macro avg       1.00      1.00      1.00        34
weighted avg       1.00      1.00      1.00        34

Accuracy score is: 1.000
Balanced accuracy score is: 1.000
Precision score is: 1.000
Recall score is: 1.000
StratifiedKFold CV Balanced Accuracy: 0.976\scriptsize(±0.08)
StratifiedKFold CV Accuracy: 0.976\scriptsize(±0.08)
StratifiedKFold CV Precision: 0.980\scriptsize(±0.07)
StratifiedKFold CV Recall: 0.976\scriptsize(±0.08)
Confusion matrix: 
[[17  0]
 [ 0 17]]
Classification report:    

In [16]:
#SVM
from sklearn.svm import SVC 
cv_results1 = implement(SVC(max_iter = -1, random_state=10),
                     x_train1, y_train1, x_test1, y_test1, x_ds1, y_ds1)

cv_results2 = implement(SVC(max_iter = -1, random_state=10),
                     x_train2, y_train2, x_test2, y_test2, x_ds2, y_ds2)

cv_results3 = implement(SVC(max_iter = -1, random_state=10),
                     x_train3, y_train3, x_test3, y_test3, x_ds3, y_ds3)

cv_results4 = implement(SVC(max_iter = -1, random_state=10),
                     x_train4, y_train4, x_test4, y_test4, x_ds4, y_ds4)

cv_results5 = implement(SVC(max_iter = -1, random_state=10),
                     x_train5, y_train5, x_test5, y_test5, x_ds5, y_ds5)

cv_results6 = implement(SVC(max_iter = -1, random_state=10),
                     x_train6, y_train6, x_test6, y_test6, x_ds6, y_ds6)

cv_results7 = implement(SVC(max_iter = -1, random_state=10),
                     x_train7, y_train7, x_test7, y_test7, x_ds7, y_ds7)

cv_results8 = implement(SVC(max_iter = -1, random_state=10),
                     x_train8, y_train8, x_test8, y_test8, x_ds8, y_ds8)

compute_model_differences("svm", globals())

Confusion matrix: 
[[216   0  11   0   1   1   4]
 [  0 118   0   0   0   0   0]
 [ 10   0 313   0   5   1   1]
 [  0   0   0 644   1   9  52]
 [  0   0   8   7 369   0  12]
 [  6   0   0  10   0 383  12]
 [  0   0   0  41  10   8 470]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.93      0.93      0.93       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.94      0.95      0.95       330
    DERMASON       0.92      0.91      0.91       706
       HOROZ       0.96      0.93      0.94       396
       SEKER       0.95      0.93      0.94       411
        SIRA       0.85      0.89      0.87       529

    accuracy                           0.92      2723
   macro avg       0.94      0.93      0.94      2723
weighted avg       0.92      0.92      0.92      2723

Accuracy score is: 0.923
Balanced accuracy score is: 0.934
Precision score is: 0.924
Recall score is: 0.923
StratifiedKFold CV Balanced Accurac

In [17]:
#Gaussian Naive Bayes
from sklearn.naive_bayes import GaussianNB 

cv_results1 = implement(GaussianNB(),
                     x_train1, y_train1, x_test1, y_test1, x_ds1, y_ds1)

cv_results2 = implement(GaussianNB(),
                     x_train2, y_train2, x_test2, y_test2, x_ds2, y_ds2)

cv_results3 = implement(GaussianNB(),
                     x_train3, y_train3, x_test3, y_test3, x_ds3, y_ds3)

cv_results4 = implement(GaussianNB(),
                     x_train4, y_train4, x_test4, y_test4, x_ds4, y_ds4)

cv_results5 = implement(GaussianNB(),
                     x_train5, y_train5, x_test5, y_test5, x_ds5, y_ds5)

cv_results6 = implement(GaussianNB(),
                     x_train6, y_train6, x_test6, y_test6, x_ds6, y_ds6)

cv_results7 = implement(GaussianNB(),
                     x_train7, y_train7, x_test7, y_test7, x_ds7, y_ds7)

cv_results8 = implement(GaussianNB(),
                     x_train8, y_train8, x_test8, y_test8, x_ds8, y_ds8)

compute_model_differences("gnb", globals())

Confusion matrix: 
[[179   0  42   0   0   1  11]
 [  1 117   0   0   0   0   0]
 [ 27   0 297   0   4   1   1]
 [  0   0   0 604   0  20  82]
 [  0   0  11   6 365   0  14]
 [  5   0   0   5   0 387  14]
 [  6   0   0  27  11  14 471]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.82      0.77      0.79       233
      BOMBAY       1.00      0.99      1.00       118
        CALI       0.85      0.90      0.87       330
    DERMASON       0.94      0.86      0.90       706
       HOROZ       0.96      0.92      0.94       396
       SEKER       0.91      0.94      0.93       411
        SIRA       0.79      0.89      0.84       529

    accuracy                           0.89      2723
   macro avg       0.90      0.90      0.90      2723
weighted avg       0.89      0.89      0.89      2723

Accuracy score is: 0.889
Balanced accuracy score is: 0.896
Precision score is: 0.892
Recall score is: 0.889
StratifiedKFold CV Balanced Accurac

In [18]:
#Random Forests
from sklearn.ensemble import RandomForestClassifier

cv_results1 = implement(RandomForestClassifier(),
                     x_train1, y_train1, x_test1, y_test1, x_ds1, y_ds1)

cv_results2 = implement(RandomForestClassifier(),
                     x_train2, y_train2, x_test2, y_test2, x_ds2, y_ds2)

cv_results3 = implement(RandomForestClassifier(),
                     x_train3, y_train3, x_test3, y_test3, x_ds3, y_ds3)

cv_results4 = implement(RandomForestClassifier(),
                     x_train4, y_train4, x_test4, y_test4, x_ds4, y_ds4)

cv_results5 = implement(RandomForestClassifier(),
                     x_train5, y_train5, x_test5, y_test5, x_ds5, y_ds5)

cv_results6 = implement(RandomForestClassifier(),
                     x_train6, y_train6, x_test6, y_test6, x_ds6, y_ds6)

cv_results7 = implement(RandomForestClassifier(),
                     x_train7, y_train7, x_test7, y_test7, x_ds7, y_ds7)

cv_results8 = implement(RandomForestClassifier(),
                     x_train8, y_train8, x_test8, y_test8, x_ds8, y_ds8)

compute_model_differences("rf", globals())

Confusion matrix: 
[[215   0  10   0   1   2   5]
 [  0 118   0   0   0   0   0]
 [ 13   0 309   0   6   1   1]
 [  0   0   0 645   2   8  51]
 [  2   0   6   8 368   0  12]
 [  2   0   0  15   0 382  12]
 [  2   0   1  51   6   9 460]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.92      0.92      0.92       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.95      0.94      0.94       330
    DERMASON       0.90      0.91      0.91       706
       HOROZ       0.96      0.93      0.94       396
       SEKER       0.95      0.93      0.94       411
        SIRA       0.85      0.87      0.86       529

    accuracy                           0.92      2723
   macro avg       0.93      0.93      0.93      2723
weighted avg       0.92      0.92      0.92      2723

Accuracy score is: 0.917
Balanced accuracy score is: 0.929
Precision score is: 0.918
Recall score is: 0.917
StratifiedKFold CV Balanced Accurac

In [19]:
#Decesion Trees
from sklearn.tree import DecisionTreeClassifier


cv_results1 = implement(DecisionTreeClassifier(),
                     x_train1, y_train1, x_test1, y_test1, x_ds1, y_ds1)

cv_results2 = implement(DecisionTreeClassifier(),
                     x_train2, y_train2, x_test2, y_test2, x_ds2, y_ds2)

cv_results3 = implement(DecisionTreeClassifier(),
                     x_train3, y_train3, x_test3, y_test3, x_ds3, y_ds3)

cv_results4 = implement(DecisionTreeClassifier(),
                     x_train4, y_train4, x_test4, y_test4, x_ds4, y_ds4)

cv_results5 = implement(DecisionTreeClassifier(),
                     x_train5, y_train5, x_test5, y_test5, x_ds5, y_ds5)

cv_results6 = implement(DecisionTreeClassifier(),
                     x_train6, y_train6, x_test6, y_test6, x_ds6, y_ds6)

cv_results7 = implement(DecisionTreeClassifier(),
                     x_train7, y_train7, x_test7, y_test7, x_ds7, y_ds7)

cv_results8 = implement(DecisionTreeClassifier(),
                     x_train8, y_train8, x_test8, y_test8, x_ds8, y_ds8)

compute_model_differences("dt", globals())

Confusion matrix: 
[[208   0  16   0   2   1   6]
 [  0 118   0   0   0   0   0]
 [ 13   0 304   0   9   2   2]
 [  0   0   0 621   3  15  67]
 [  4   0   8   6 360   0  18]
 [  5   0   0  12   0 372  22]
 [  6   0   4  69   3  17 430]]
Classification report:               precision    recall  f1-score   support

    BARBUNYA       0.88      0.89      0.89       233
      BOMBAY       1.00      1.00      1.00       118
        CALI       0.92      0.92      0.92       330
    DERMASON       0.88      0.88      0.88       706
       HOROZ       0.95      0.91      0.93       396
       SEKER       0.91      0.91      0.91       411
        SIRA       0.79      0.81      0.80       529

    accuracy                           0.89      2723
   macro avg       0.90      0.90      0.90      2723
weighted avg       0.89      0.89      0.89      2723

Accuracy score is: 0.886
Balanced accuracy score is: 0.903
Precision score is: 0.887
Recall score is: 0.886
StratifiedKFold CV Balanced Accurac

Comparison results for futher use at LaTex table format

In [20]:
print (f"""
Beans 
& accuracy
& {knn_0_bacc}
& {ada_0_bacc}
& {svm_0_bacc}
& {gnb_0_bacc}
& {rf_0_bacc}
& {dt_0_bacc}
\\\\
Beans 
& precision 
& {knn_0_precision}
& {ada_0_precision}
& {svm_0_precision}
& {gnb_0_precision}
& {rf_0_precision}
& {dt_0_precision}
\\\\
Beans 
& recall 
& {knn_0_recall}
& {ada_0_recall}
& {svm_0_recall}
& {gnb_0_recall}
& {rf_0_recall}
& {dt_0_recall}
\\\\Divorce 
& accuracy
& {knn_1_bacc}
& {ada_1_bacc}
& {svm_1_bacc}
& {gnb_1_bacc}
& {rf_1_bacc}
& {dt_1_bacc}
\\\\
Divorce 
& precision 
& {knn_1_precision}
& {ada_1_precision}
& {svm_1_precision}
& {gnb_1_precision}
& {rf_1_precision}
& {dt_1_precision}
\\\\
Divorce
& recall 
& {knn_1_recall}
& {ada_1_recall}
& {svm_1_recall}
& {gnb_1_recall}
& {rf_1_recall}
& {dt_1_recall}
\\\\Parkinson's 
& accuracy
& {knn_2_bacc}
& {ada_2_bacc}
& {svm_2_bacc}
& {gnb_2_bacc}
& {rf_2_bacc}
& {dt_2_bacc}
\\\\
Parkinson's 
& precision 
& {knn_2_precision}
& {ada_2_precision}
& {svm_2_precision}
& {gnb_2_precision}
& {rf_2_precision}
& {dt_2_precision} 
\\\\
Parkinson's 
& recall 
& {knn_2_recall}
& {ada_2_recall}
& {svm_2_recall}
& {gnb_2_recall}
& {rf_2_recall}
& {dt_2_recall}
\\\\
Rice 
& accuracy
& {knn_3_bacc}
& {ada_3_bacc}
& {svm_3_bacc}
& {gnb_3_bacc}
& {rf_3_bacc}
& {dt_3_bacc}
\\\\
Rice 
& precision 
& {knn_3_precision}
& {ada_3_precision}
& {svm_3_precision}
& {gnb_3_precision}
& {rf_3_precision}
& {dt_3_precision}
\\\\
Rice 
& recall 
& {knn_3_recall}
& {ada_3_recall}
& {svm_3_recall}
& {gnb_3_recall}
& {rf_3_recall}
& {dt_3_recall}
\\\\
""")


Beans 
& accuracy
& -0.028 \scriptsize(\%3.0)
& -0.004 \scriptsize(\%0.5)
& -0.017 \scriptsize(\%1.8)
& -0.012 \scriptsize(\%1.3)
& -0.019 \scriptsize(\%2.0)
& -0.004 \scriptsize(\%0.4)
\\
Beans 
& precision 
& -0.027 \scriptsize(\%3.0)
& -0.001 \scriptsize(\%0.1)
& -0.013 \scriptsize(\%1.4)
& -0.011 \scriptsize(\%1.2)
& -0.017 \scriptsize(\%1.8)
& +0.002 \scriptsize(\%0.2)
\\
Beans 
& recall 
& -0.032 \scriptsize(\%3.5)
& -0.003 \scriptsize(\%0.4)
& -0.014 \scriptsize(\%1.5)
& -0.011 \scriptsize(\%1.2)
& -0.017 \scriptsize(\%1.8)
& +0.002 \scriptsize(\%0.2)
\\Divorce 
& accuracy
& 0
& 0
& 0
& +0.006 \scriptsize(\%0.6)
& 0
& +0.017 \scriptsize(\%1.8)
\\
Divorce 
& precision 
& 0
& 0
& 0
& +0.007 \scriptsize(\%0.7)
& 0
& +0.018 \scriptsize(\%1.9)
\\
Divorce
& recall 
& 0
& 0
& 0
& +0.006 \scriptsize(\%0.6)
& 0
& +0.018 \scriptsize(\%1.9)
\\Parkinson's 
& accuracy
& -0.078 \scriptsize(\%8.7)
& -0.076 \scriptsize(\%9.0)
& +0.016 \scriptsize(\%2.1)
& -0.003 \scriptsize(\%0.4)
& -0.049 \sc